=== shjjgg/SurvivalcraftApi-SCAPI1.9/Survivalcraft/Content/Assets/Clothes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:complexType name="ClothesType">
        <xs:sequence>
            <xs:element ref="ClothingData" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Clothes" type="ClothesType" />
    <xs:element name="Mod" type="ClothesType" />

    <xs:element name="ClothingData">
        <xs:complexType>
            <xs:attribute name="Class" type="xs:string" default="Game.ClothingData" />
            <xs:attribute name="New-Class" type="xs:string" default="Game.ClothingData" />
            <xs:attribute name="Index" use="required" type="IndexType" />
            <xs:attribute name="DisplayIndex" type="IndexType" />
            <xs:attribute name="New-DisplayIndex" type="IndexType" />
            <xs:attribute name="DisplayName" type="xs:string" />
            <xs:attribute name="New-DisplayName" type="xs:string" />
            <xs:attribute name="Description" type="xs:string" />
            <xs:attribute name="New-Description" type="xs:string" />
            <xs:attribute name="Slot" type="SlotType" />
            <xs:attribute name="New-Slot" type="SlotType" />
            <xs:attribute name="ArmorProtection" type="xs:float" />
            <xs:attribute name="New-ArmorProtection" type="xs:float" />
            <xs:attribute name="Sturdiness" type="xs:float" />
            <xs:attribute name="New-Sturdiness" type="xs:float" />
            <xs:attribute name="Insulation" type="xs:float" />
            <xs:attribute name="New-Insulation" type="xs:float" />
            <xs:attribute name="MovementSpeedFactor" type="xs:float" />
            <xs:attribute name="New-MovementSpeedFactor" type="xs:float" />
            <xs:attribute name="SteedMovementSpeedFactor" type="xs:float" />
            <xs:attribute name="New-SteedMovementSpeedFactor" type="xs:float" />
            <xs:attribute name="DensityModifier" type="xs:float" />
            <xs:attribute name="New-DensityModifier" type="xs:float" />
            <xs:attribute name="IsOuter" type="Bollean" />
            <xs:attribute name="New-IsOuter" type="Bollean" />
            <xs:attribute name="CanBeDyed" type="Bollean" />
            <xs:attribute name="New-CanBeDyed" type="Bollean" />
            <xs:attribute name="Layer" type="xs:int" />
            <xs:attribute name="New-Layer" type="xs:int" />
            <xs:attribute name="PlayerLevelRequired" type="xs:int" />
            <xs:attribute name="New-PlayerLevelRequired" type="xs:int" />
            <xs:attribute name="TextureName" type="xs:string" />
            <xs:attribute name="New-TextureName" type="xs:string" />
            <xs:attribute name="ImpactSoundsFolder" type="xs:string" />
            <xs:attribute name="New-ImpactSoundsFolder" type="xs:string" />
            <xs:attribute name="Remove" type="xs:string" />
            <xs:anyAttribute />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="Bollean">
        <xs:restriction base="xs:string">
            <xs:enumeration value="True" />
            <xs:enumeration value="False" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="IndexType">
        <xs:restriction base="xs:unsignedInt">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="1023" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="SlotType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Head" />
            <xs:enumeration value="Torso" />
            <xs:enumeration value="Legs" />
            <xs:enumeration value="Feet" />
            <xs:pattern value=".*" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== shjjgg/SurvivalcraftApi-SCAPI1.9/Survivalcraft/Content/Assets/Clothes.xml
<Clothes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Clothes.xsd">
  <ClothingData Class="Game.ClothingData" Index="32" DisplayName="[ClothingBlock:32]" Description="[ClothingBlock:32]" Slot="Head" ArmorProtection="0.1" Sturdiness="25" Insulation="4.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/OldHat" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="37" DisplayName="[ClothingBlock:37]" Description="[ClothingBlock:37]" Slot="Torso" ArmorProtection="0.1" Sturdiness="25" Insulation="1.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="0" PlayerLevelRequired="1" TextureName="Textures/Clothing/OldTankTop" ImpactSoundsFolder="" />
  <ClothingData Class="Game.ClothingData" Index="1" DisplayName="[ClothingBlock:1]" Description="[ClothingBlock:1]" Slot="Torso" ArmorProtection="0.1" Sturdiness="25" Insulation="2.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/OldShirt" ImpactSoundsFolder="" />
  <ClothingData Class="Game.ClothingData" Index="0" DisplayName="[ClothingBlock:0]" Description="[ClothingBlock:0]" Slot="Legs" ArmorProtection="0.1" Sturdiness="25" Insulation="2.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/OldPants" ImpactSoundsFolder="" />

  <ClothingData Class="Game.ClothingData" Index="30" DisplayName="[ClothingBlock:30]" Description="[ClothingBlock:30]" Slot="Head" ArmorProtection="0.1" Sturdiness="25" Insulation="4.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonFedora" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="13" DisplayName="[ClothingBlock:13]" Description="[ClothingBlock:13]" Slot="Torso" ArmorProtection="0.1" Sturdiness="25" Insulation="4.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonShirt" ImpactSoundsFolder="" />
  <ClothingData Class="Game.ClothingData" Index="14" DisplayName="[ClothingBlock:14]" Description="[ClothingBlock:14]" Slot="Torso" ArmorProtection="0.1" Sturdiness="25" Insulation="2.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="0" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonTShirt" ImpactSoundsFolder="" />
  <ClothingData Class="Game.ClothingData" Index="15" DisplayName="[ClothingBlock:15]" Description="[ClothingBlock:15]" Slot="Torso" ArmorProtection="0.1" Sturdiness="25" Insulation="1.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="0" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonTankTop" ImpactSoundsFolder="" />
  <ClothingData Class="Game.ClothingData" Index="16" DisplayName="[ClothingBlock:16]" Description="[ClothingBlock:16]" Slot="Legs" ArmorProtection="0.1" Sturdiness="25" Insulation="4.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonPants" ImpactSoundsFolder="" />
  <ClothingData Class="Game.ClothingData" Index="17" DisplayName="[ClothingBlock:17]" Description="[ClothingBlock:17]" Slot="Legs" ArmorProtection="0.1" Sturdiness="25" Insulation="1.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonShorts" ImpactSoundsFolder="" />

  <ClothingData Class="Game.ClothingData" Index="24" DisplayName="[ClothingBlock:24]" Description="[ClothingBlock:24]" Slot="Torso" ArmorProtection="0.1" Sturdiness="25" Insulation="12.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="2" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonSweater" ImpactSoundsFolder="" />
  <ClothingData Class="Game.ClothingData" Index="25" DisplayName="[ClothingBlock:25]" Description="[ClothingBlock:25]" Slot="Legs" ArmorProtection="0.1" Sturdiness="25" Insulation="12.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="0" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonLongJohns" ImpactSoundsFolder="" />
  <ClothingData Class="Game.ClothingData" Index="26" DisplayName="[ClothingBlock:26]" Description="[ClothingBlock:26]" Slot="Feet" ArmorProtection="0.1" Sturdiness="25" Insulation="8.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="0" PlayerLevelRequired="1" TextureName="Textures/Clothing/CottonSocks" ImpactSoundsFolder="" />

  <ClothingData Class="Game.ClothingData" Index="31" DisplayName="[ClothingBlock:31]" Description="[ClothingBlock:31]" Slot="Head" ArmorProtection="0.5" Sturdiness="40" Insulation="8.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/LeatherCowboyHat" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="11" DisplayName="[ClothingBlock:11]" Description="[ClothingBlock:11]" Slot="Head" ArmorProtection="0.5" Sturdiness="40" Insulation="8.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/LeatherHat" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="5" DisplayName="[ClothingBlock:5]" Description="[ClothingBlock:5]" Slot="Torso" ArmorProtection="0.5" Sturdiness="40" Insulation="4.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="2" PlayerLevelRequired="1" TextureName="Textures/Clothing/LeatherJerkin" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="12" DisplayName="[ClothingBlock:12]" Description="[ClothingBlock:12]" Slot="Legs" ArmorProtection="0.5" Sturdiness="40" Insulation="4.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="False" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/LeatherPants" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="29" DisplayName="[ClothingBlock:29]" Description="[ClothingBlock:29]" Slot="Feet" ArmorProtection="0.5" Sturdiness="20" Insulation="8.0" MovementSpeedFactor="1.2" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/LeatherSandals" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="8" DisplayName="[ClothingBlock:8]" Description="[ClothingBlock:8]" Slot="Feet" ArmorProtection="0.5" Sturdiness="40" Insulation="12.0" MovementSpeedFactor="1.25" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/LeatherBoots" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="27" DisplayName="[ClothingBlock:27]" Description="[ClothingBlock:27]" Slot="Feet" ArmorProtection="0.75" Sturdiness="60" Insulation="16.0" MovementSpeedFactor="1.25" SteedMovementSpeedFactor="1.05" DensityModifier="0.0" IsOuter="True" CanBeDyed="False" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/CavalryBoots" ImpactSoundsFolder="Audio/Impacts/Soft" />

  <ClothingData Class="Game.ClothingData" Index="18" DisplayName="[ClothingBlock:18]" Description="[ClothingBlock:18]" Slot="Head" ArmorProtection="0.25" Sturdiness="30" Insulation="16.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="1" PlayerLevelRequired="1" TextureName="Textures/Clothing/FurHat" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="6" DisplayName="[ClothingBlock:6]" Description="[ClothingBlock:6]" Slot="Torso" ArmorProtection="0.25" Sturdiness="30" Insulation="16.0" MovementSpeedFactor="0.95" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="4" PlayerLevelRequired="1" TextureName="Textures/Clothing/FurCoat" ImpactSoundsFolder="Audio/Impacts/Soft" />
  <ClothingData Class="Game.ClothingData" Index="7" DisplayName="[ClothingBlock:7]" Description="[ClothingBlock:7]" Slot="Legs" ArmorProtection="0.25" Sturdiness="30" Insulation="16.0" MovementSpeedFactor="0.95" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="True" Layer="4" PlayerLevelRequired="1" TextureName="Textures/Clothing/FurLeggings" ImpactSoundsFolder="Audio/Impacts/Soft" />

  <ClothingData Class="Game.ClothingData" Index="23" DisplayName="[ClothingBlock:23]" Description="[ClothingBlock:23]" Slot="Torso" ArmorProtection="1.0" Sturdiness="15" Insulation="0.0" MovementSpeedFactor="1" SteedMovementSpeedFactor="1" DensityModifier="0.0" IsOuter="True" CanBeDyed="False" Layer="4" PlayerLevelRequired="1" TextureName="Textures/Clothing/WoodenChestPlate" ImpactSoundsFolder="Audio/Impacts/Wood" />
